Includes a function to help the ground support downloading sat images.
orcestra-campaign/pyorcestra pull request #95
Opened 2024-09-19 20:17 UTC by JuliaWindmiller1987

The function downloads a GOES image with predefinded corner coordinates and saves it under a comprehensive file name.

2024-09-19 22:14 UTC, lkluft requested changes
Thanks for adding this! :) I made two minor comments that you may want to address before merging

2024-09-19 22:14 UTC, lkluft commented on orcestra/sat.py
> +    filename = f"{time}_{bbox}_{layer}.jpg"
Commas in filenames are a bit annoying, you may want to replace them in the filename
```suggestion
    filename = f"{time}_{bbox}_{layer}.jpg".replace(",", "")
```

2024-09-19 22:14 UTC, lkluft commented on orcestra/sat.py
> +            os.makedirs(folder_path)
```suggestion
        os.makedirs(folder_path, exist_ok=True)
```

2024-09-20 01:30 UTC, JuliaWindmiller1987 commented on orcestra/sat.py
> +            os.makedirs(folder_path)
Ah, nice, I did not know this!

2024-09-20 01:31 UTC, merged